### ISSUE TITLE
ncr executable sometime fails in github CI

### ISSUE THREAD

**Issue by matteo-cristino** [ForkbombEu/ncr#146]
When using the ncr binary from github CI sometime randomaly I get
```
pkg/prelude/bootstrap.js:1926
      return wrapper.apply(this.exports, args);
                     ^

Error: This version of uWS.js supports only Node.js LTS versions 16, 18 and 20 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

Error: /tmp/pkg/8587103d6a12b0e5ed732a11cbaf94ec2a6f7b899f3d72c40c577accb5a41d1b/uws_linux_x64_108.node: file too short
    at /snapshot/ncr/dist/index.cjs
    at Object.<anonymous> (/snapshot/ncr/dist/index.cjs)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.5.0
```

**Comment by puria** [comment]
🧐 Seems something we can report directly to https://github.com/uNetworking/uWebSockets.js

**Comment by matteo-cristino** [comment]
They said it is not an issue on their side

https://github.com/uNetworking/uWebSockets.js/issues/1053

**Comment by puria** [comment]
Is this still an issue?

**Comment by matteo-cristino** [comment]
It is a bit that I do not see it anymore, but I am not running as much the DIDRoom_microservices CI as we did one month ago. Will see it in the following days when we should start working again on that folder

**Comment by puria** [comment]
is this still an issue? aahahah I made the same comment, hoping that this will disappear, alooone, in a magic way

**Comment by matteo-cristino** [comment]
lately I tried to add a sleep of 5 seconds between the ncr starts and it seems to have resolved the problem
