### ISSUE TITLE
If specified port is already taken, the app dies

### ISSUE THREAD

**Issue by bbtgnn** [ForkbombEu/ncr#22]
Add a human readable error to explain what's happening

**Comment by bbtgnn** [comment]
I'm having issues trying to reproduce the issue.

I launched:
- a server with `python -m http.server 8000 --bind 0.0.0.0`
- ncr with `pnpm dev -p 8000 --hostname 0.0.0.0`

But I don't get any errors. @puria do you have any ideas?

**Comment by puria** [comment]
OK! Yes I can do that also when you don't have permission to open the port... like use a port under 300...

**Comment by puria** [comment]
prova con la 80... a milano c'è il 🌞

**Comment by bbtgnn** [comment]
Non si rompe eheh

**Comment by puria** [comment]
È una bomba, l'ho sempre saputo! have you tried both from the `.env` and from the cli arguments?

**Comment by bbtgnn** [comment]
yuppp

**Comment by puria** [comment]
@bbtgnn I guess that the environment variable PORT is clashing, plz rename all the variables to have more specific names eg. NCR_PORT

**Comment by bbtgnn** [comment]
I am not sure about it, cause I tried to run it with command line options

Il giorno mar 12 dic 2023 alle 12:53 Puria Nafisi Azizi <
***@***.***> ha scritto:

**Comment by puria** [comment]
The point is that docker uses the same env vriable that we use... namely: PORT
so docker and ncr both try to rear the same var... if you change it to PORT_NCR or something different that should be safer. If you try it and is not yet an issue, we can close this!
