### ISSUE TITLE
Run documentation. Tutorial. Examples

### ISSUE THREAD

**Issue by puria** [ForkbombEu/ncr#291]
Provide some docs to allow people to adopt more easily ncr

- [ ] Tutorial of a service
- [ ] Document well the metadata options. Maybe also separated by subjects
- [ ] A set of nice and running examples
- [ ] Refresh the --help of the CLI

**Comment by matteo-cristino** [comment]
Isn't this stuff already in the README.md? 🤔

**Comment by puria** [comment]
Nope ;( 
Let's start one by one... I do not recall a tutorial, something is needed step by step that explains how to start using ncr and explains also the concepts with a simple usecase.

Something like this:

https://medium.com/think-do-tank/make-with-zencode-and-javascript-aka-easy-crypto-and-human-readable-smart-contracts-in-js-14067d91e8f1

To me we can use for instance this contracts:
https://github.com/ForkbombEu/tf-pqcrypto-scripts/tree/main/contracts

**Comment by matteo-cristino** [comment]
do you want to improve the README or should we create some external documentation? For example using again vitepress

**Comment by puria** [comment]
external doc but under slangroom docs... we need an `Echosystem` page that explains how to use slangroom:

cli => cliroom / slangroom-exec / gemini
http => ncr / gemini
browser => just html import with the cdn
bindings => golang/js for now

**Comment by matteo-cristino** [comment]
Then will move this issue to slangroom repo 🚀
