### ISSUE TITLE
NCR doesn't know most codecs and schema

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/ncr#33]
Zencode

```
Given I have a 'keyring' 
Given I have a 'string' named 'message' 

Then print data

```
DATA:

`{"message": "peppe"}`

produces: 

https://gyazo.com/c2f24c45c2126df5808ec21cdbf98716

and

https://gyazo.com/302be2f9988af428674766c90bd08ecb

-----------------

The same behaviour happens with: 

```
Given I have a 'string' named 'message' 
Given I have a 'base64' named 'a'
Given I have a 'base58' named 'b'
Given I have a 'hex' named 'c'
Given I have a 'number array' named 'd'
Given I have a 'string array' named 'e'
Given I have a 'base64 array' named 'f'
Given I have a 'base58 array' named 'g'

Then print data
```

**Comment by puria** [comment]
This is related to zenroom introspection. But @matteo-cristino have done already a lot of improvements! Not a definitive solution but inside the applets now you can choose the type format for the data fields
