### ISSUE TITLE
Add link in app page

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/ncr#397]
In the app page, the link to the app is very hidden... ideally there should be a promininet HTML link introduce by "click here to open the app"

See: https://gyazo.com/5f92ac6d008252de4cccb58b609a3fd0

And this link works: http://ec2-13-38-56-165.eu-west-3.compute.amazonaws.com:8080/ml-dsa44-sign/app

**Comment by puria** [comment]
not possible
