### ISSUE TITLE
Multiple renames

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/ncr#398]
1) the term "contract" is internal only, we should use "script" or "zencode"
2) zencode is always singular (e.g. "Javas"? )
3) "Zencode" should not be confused with the APIs.

So the for the left menu **ENDPOINTS**

I recommend: 

1) Zencode APIs
2) Zencode Applets
3) Zencode (raw scripts)

**Comment by puria** [comment]
I like the suggestions! Bravo 😽

**Comment by puria** [comment]
@andrea-dintino please a PR is welcome, you can change them directly here: https://github.com/ForkbombEu/ncr/blob/main/src/openapi.ts#L12-L14
