### ISSUE TITLE
Zencode script causes NCR to crash

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/ncr#50]
Zencode: 

```
Given I have a 'float' named 'Principal'
Given I have a 'float' named 'InterestRate'
Given I have a 'float' named 'DownPaymentPercent'
Given I have a 'float' named 'InvestorX'
Given I have a 'float' named 'InvestorY'
Given I have a 'float' named 'InvestorZ'
Given I have a 'float' named 'Months'

When I create the result of 'Principal' * 'DownPaymentPercent'
When I rename the 'result' to 'DownPayment'
When I create the result of 'Principal' - 'DownPayment'
When I rename the 'result' to 'MortgageAmount'


When I create the result of 'MortgageAmount' * 'InterestRate'
When I rename the 'result' to 'temp'
When I create the result of 'temp' / 'Months'
When I rename the 'result' to 'MonthlyInterest'



When I create the result of 'InvestorX' * 'MonthlyInterest'
When I rename the 'result' to 'InvestorXDistribution'
When I create the result of 'InvestorY' * 'MonthlyInterest'
When I rename the 'result' to 'InvestorYDistribution'
When I create the result of 'InvestorZ' * 'MonthlyInterest'
When I rename the 'result' to 'InvestorZDistribution'

# then print data

Then print the 'InvestorXDistribution'
Then print the 'InvestorYDistribution'
Then print the 'InvestorZDistribution'
Then print the 'MonthlyInterest'

```
Keys

```
{
	"Months": 12
}

```
Data 

```
{
	"Principal": 200000,
	"InterestRate": 0.06,
	"InvestorX": 0.5,
	"InvestorY": 0.3,
	"InvestorZ": 0.2,
	"DownPaymentPercent": 0.2
}

```

Issues (the appear when clicking the "Press this" button: 
https://gyazo.com/4f47dfe7373af4f2d36009c875e71bb8
https://gyazo.com/d6a54973a5d4bfcc392c175393fbf15d

**Comment by puria** [comment]
Thanks! This is very useful!

I'm not able to reproduce it, althoug ;(
![Screenshot from 2024-02-13 at 02_32_21 259819759](https://github.com/ForkbombEu/ncr/assets/10379/046c1841-9679-42ff-bf28-f7b55bd1978e)

Is there a specific amount you are trying to input (In data I mean) does that work seamlessly on `zenroom` from CLI?

**Comment by andrea-dintino** [comment]
We could reproduce this SATANIC issue: it only occurs if you use a .conf along with the script, with any .config, for example

debug=3, rngseed=hex:74eeeab870a394175fae808dd5dd3b047f3ee2d6a8d01e14bff94271565625e98a63babe8dd6cbea6fedf3e19de4bc80314b861599522e44409fdd20f7cd6cfc

We're testing Slangroom atm

**Comment by andrea-dintino** [comment]
The issue was due to: https://github.com/dyne/slangroom/issues/70
